### ISSUE TITLE
repository structure

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/sample-encodings#1]
Wouldn't it be better for long-term maintenance to rename the top-level 3.0.0 folder to "current"?  This folder could always hold the latest examples without having to rename the folder each time.

**Comment by ahankinson** [comment]
No problems with that; however, to provide a counter-point, we can always just move '3.0.0' to 'legacy' and then generate '3.1' or '4.0' from there. 

But I can see the benefits of both. If there isn't a strong consensus expressed I will change it to 'current.'
