### ISSUE TITLE
Problems in pop/jazz music samples

### ISSUE THREAD

**Issue by th-we** [music-encoding/sample-encodings#14]
Both [`McFerrin_Don't_worry.mei`](https://github.com/music-encoding/sample-encodings/blob/5fba3a447513e11ed5bbe6545a7b227a9ed0e735/MEI%203.0/Music/Complete%20examples/McFerrin_Don't_worry.mei) and [`Parker-Gillespie_ShawNuff.mei`](https://github.com/music-encoding/sample-encodings/blob/5fba3a447513e11ed5bbe6545a7b227a9ed0e735/MEI%203.0/Music/Complete%20examples/Parker-Gillespie_ShawNuff.mei) have problems with the rhythmic notation above the staff. The problems I see:

* They need to be in a separate layer (sometimes they are, sometimes not)
* I don't think `@pname` and `@oct` attributes are appropriate.  Maybe `@loc`?
* Frequently, they're lacking `@dur`

Additionally, I see some issues with text in `Parker-Gillespie_ShawNuff.mei`.

* Things that don't belong together shouldn't be combined in one `<dir>`, only separated by a line break (`<lb>`). As an example: [`MI(MAT) (trp.<lb/>alto)`](https://github.com/music-encoding/sample-encodings/blob/5fba3a447513e11ed5bbe6545a7b227a9ed0e735/MEI%203.0/Music/Complete%20examples/Parker-Gillespie_ShawNuff.mei#L411) in measure 5 - where "MI(MAT)" should actually be "MI(MA7)" and part of something like `<harm>BbMI(MA7)</harm>`. However, I'm not sure how to write the chords, that's a little underspecified in MEI.
* `N.C.` actually means "no chords" - should we put it in a `<harm>` as well?  It's structurally the same thing as a chord symbol - in the PDF, it typographically uses the font/size combination that is unique to chord symbols.

**Comment by pe-ro** [comment]
These problems (I think) originated with the initial conversion from MusicXML to MEI.  But, without access to the original, it's difficult to fix them all.

I fixed the dir/harm confusion for "N.C." and the `<lb/>` issue. But exact placement of the results may still be "off".
