### ISSUE TITLE
filenames with "ö" character

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/sample-encodings#2]
When I clone the repo to my local machine (Mac OS X 10.8.5) the sample encodings with "ö" in the name e.g. "Schubert_Erlkönig.mei" will be presented to me as "untracked" files in git command line. This seems to be due to somw OS based character encoding as the the files will be listed as something like "Schubert_Erlk\314\210nig.mei"

**Comment by ahankinson** [comment]
Seems to be a common problem -- try running `git config --global core.precomposeunicode true` and see if that fixes it.

**Comment by bwbohl** [comment]
did fix it
