### ISSUE TITLE
Incorrect beam in Bach_Ein_festeBurg.mei

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/sample-encodings#20]
In measure 4 of Bach_Ein_festeBurg.mei, there are two beam groups which contain a quarter note:

https://github.com/music-encoding/sample-encodings/blob/5fba3a/MEI%203.0/Music/Complete%20examples/Bach_Ein_festeBurg.mei#L670-L674

```xml
                           <beam>
                              <note xml:id="d1e1269" pname="c" oct="4" dur="8" stem.dir="down"/>
                              <note xml:id="d1e1289" pname="d" oct="4" dur="4" stem.dir="down"/>
                              <note xml:id="d1e1303" pname="c" oct="4" dur="8" stem.dir="down"/>
                           </beam>
```

and

https://github.com/music-encoding/sample-encodings/blob/5fba3a/MEI%203.0/Music/Complete%20examples/Bach_Ein_festeBurg.mei#L680-L684

```xml
                           <beam>
                              <note xml:id="d1e1908" pname="e" oct="4" dur="8" stem.dir="up"/>
                              <note xml:id="d1e1926" pname="a" oct="3" dur="4" stem.dir="up"/>
                              <note xml:id="d1e1940" pname="g" oct="3" dur="8" stem.dir="up"/>
                           </beam>
```

The beam grouping should be removed on these notes.

Source PDF for this encoding:

https://github.com/music-encoding/sample-encodings/blob/5fba3a447513e11ed5bbe6545a7b227a9ed0e735/MEI%203.0/Music/Complete%20examples/Bach_Ein_festeBurg.pdf

This particular measure:

<img width="232" alt="screen shot 2017-09-30 at 6 14 05 pm" src="https://user-images.githubusercontent.com/3487289/31050802-29902b80-a60b-11e7-975f-93ad1e1537d0.png">

The beam group causes problems for verovio:

<img width="196" alt="screen shot 2017-09-30 at 6 15 29 pm" src="https://user-images.githubusercontent.com/3487289/31050814-5d0dc42c-a60b-11e7-8291-6326df853a73.png">

The notes look like eighth notes, but they retain their quarter-note durations while being beamed (which seems a reasonable thing to do given the error in the data).

**Comment by craigsapp** [comment]
Looks better:

https://github.com/music-encoding/sample-encodings/blob/935382d656b0d79e5b6166663f650dfcb1787394/MEI%203.0/Music/Complete%20examples/Bach_Ein_festeBurg.mei#L668-L675

```xml
                        <layer n="2">
                           <space xml:id="d56e8a1544"/>
                              <note xml:id="d1e1269" pname="c" oct="4" dur="8" stem.dir="down"/>
                              <note xml:id="d1e1289" pname="d" oct="4" dur="4" stem.dir="down"/>
                              <note xml:id="d1e1303" pname="c" oct="4" dur="8" stem.dir="down"/>                           
                           <note xml:id="d1e1321" pname="d" oct="4" dur="4" stem.dir="down"/>
                        </layer>
```

Is there a purpose to the `<space>` at the start of the layer (also present in layer 1 of staff 2 in the same measure)?

This space element confuses verovio, because it does not have a duration; therefore, verovio assigns a breve duration to the space:

<img width="561" alt="screen shot 2017-10-01 at 7 18 35 am" src="https://user-images.githubusercontent.com/3487289/31055514-c6dc9e24-a678-11e7-8892-138705ae356e.png">


Removing the two empty spaces:

<img width="277" alt="screen shot 2017-10-01 at 7 20 08 am" src="https://user-images.githubusercontent.com/3487289/31055530-19f4c9ce-a679-11e7-991e-cf25c4a29318.png">


Verovio assigns a breve duration to notes that have no duration ( @lpugin can explain why).  An advantage of this is that the rhythm errors are easy to see, such as when the note in measure 1 is missing a rhythm:

<img width="408" alt="screen shot 2017-10-01 at 7 29 01 am" src="https://user-images.githubusercontent.com/3487289/31055604-35cf4592-a67a-11e7-8211-a7433a453014.png">

Also there is an empty space in the last measure.

The extraneous spaces should be removed, or I can open a new issue for them :-)

**Comment by pe-ro** [comment]
I think I killed all them pesky spaces.

**Comment by craigsapp** [comment]
Yes, they are all gone.

Here is the current view, which is starting to look good for the direct display of the MEI data in verovio:

<img width="828" alt="screen shot 2017-10-01 at 4 54 37 pm" src="https://user-images.githubusercontent.com/3487289/31060467-8d355ee4-a6c9-11e7-96a2-96391ffd399c.png">

The double fermatas are data errors (I have to submit an issue for those yet :-).  There should be only one fermata encoded, unless `@sameas` is somehow used.

The weird slurs are probably related to verovio confused about their placement.  I haven't tracked down why that is happening yet, although I suspect that verovio cannot handle the slur properly if it is stored in a measure other than the same system where the slur should start.

You are still missing a fermata on the last measure, bottom staff :-)

Here is the round trip view from MEI to Humdrum to MEI again:

<img width="832" alt="screen shot 2017-10-01 at 4 55 07 pm" src="https://user-images.githubusercontent.com/3487289/31060508-0df922a4-a6ca-11e7-9ab6-5de056e559a7.png">

The slurs are correctly displayed since I move them to the place where verovio expects them.

The only problem left is automatically fixing the accidental encoding (which I will do sometime this month).
