### ISSUE TITLE
word position attributes missing from lyrics in Bach_Ein_festeBurg.mei

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/sample-encodings#21]
`<syl>` contents in Bach_Ein_festeBurg.mei do not contain `@wordpos` information about syllables being at the initial, middle, or terminal positions of complete words:

<img width="699" alt="screen shot 2017-09-30 at 6 20 53 pm" src="https://user-images.githubusercontent.com/3487289/31050844-578a3fb6-a60c-11e7-8491-90984df898ed.png">

Source PDF:

https://github.com/music-encoding/sample-encodings/blob/5fba3a447513e11ed5bbe6545a7b227a9ed0e735/MEI%203.0/Music/Complete%20examples/Bach_Ein_festeBurg.pdf

<img width="809" alt="screen shot 2017-09-30 at 6 23 10 pm" src="https://user-images.githubusercontent.com/3487289/31050849-92c85464-a60c-11e7-8c52-7a51fefe4265.png">

Example is the word "feste" which is split into two syllables:

https://github.com/music-encoding/sample-encodings/blob/5fba3a447513e11ed5bbe6545a7b227a9ed0e735/MEI%203.0/Music/Complete%20examples/Bach_Ein_festeBurg.mei#L202-L217

```xml
                              <note pname="d" oct="5" dur="4" stem.dir="up">
                                 <verse n="1">
                                    <syl>fe</syl>
                                 </verse>
                                 <verse n="2">
                                    <syl>hilft</syl>
                                 </verse>
                              </note>
                              <note pname="d" oct="5" dur="4" stem.dir="up">
                                 <verse n="1">
                                    <syl>ste</syl>
                                 </verse>
                                 <verse n="2">
                                    <syl>uns</syl>
                                 </verse>
                              </note>
```

This should instead be:

```xml
                              <note pname="d" oct="5" dur="4" stem.dir="up">
                                 <verse n="1">
                                    <syl  con="d" wordpos="i">fe</syl>
                                 </verse>
                                 <verse n="2">
                                    <syl>hilft</syl>
                                 </verse>
                              </note>
                              <note pname="d" oct="5" dur="4" stem.dir="up">
                                 <verse n="1">
                                    <syl wordpos="t">ste</syl>
                                 </verse>
                                 <verse n="2">
                                    <syl>uns</syl>
                                 </verse>
                              </note>
```

`@con="d"` means to connect to next syllable with a dash (this is optional in verovio as it will add a dash automatically due to `@wordpos="i"`).

**Comment by craigsapp** [comment]
Looks good, the only thing left that I see is to add commas after Gott and Not:

<img width="1025" alt="screen shot 2017-10-01 at 3 32 31 pm" src="https://user-images.githubusercontent.com/3487289/31059898-d413ed64-a6bd-11e7-87cf-7b4b1e4e2ef8.png">

Source of encoding:

<img width="1301" alt="screen shot 2017-10-01 at 3 33 19 pm" src="https://user-images.githubusercontent.com/3487289/31059906-ef886318-a6bd-11e7-8282-0aadf8358ad0.png">

**Comment by pe-ro** [comment]
Done.

**Comment by craigsapp** [comment]
Looks great:

<img width="787" alt="screen shot 2017-10-01 at 4 44 24 pm" src="https://user-images.githubusercontent.com/3487289/31060390-d6554cbc-a6c7-11e7-8a87-1ab55ef28d9a.png">
