### ISSUE TITLE
floating elements not placed in reasonable locations in Bach_Ein_festeBurg.mei

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/sample-encodings#24]
In Bach_Ein_festeBurg.mei, there are several floating elements which are not in the correct or at least reasonable location.

Take for example the last fermata in the data:

https://github.com/music-encoding/sample-encodings/blob/5fba3a447513e11ed5bbe6545a7b227a9ed0e735/MEI%203.0/Music/Complete%20examples/Bach_Ein_festeBurg.mei#L1313

```xml
                     <fermata staff="2" startid="#d1e4245" form="inv" place="below"/>
```

This fermata is stored in measure 13, but the `@startid` of the fermata points to a note in measure 11:

https://github.com/music-encoding/sample-encodings/blob/5fba3a447513e11ed5bbe6545a7b227a9ed0e735/MEI%203.0/Music/Complete%20examples/Bach_Ein_festeBurg.mei#L1196-L1201

```xml
                           <note xml:id="d1e4245"
                                 pname="b"
                                 oct="2"
                                 dur="4"
                                 fermata="below"
                                 stem.dir="down"/>
```

Maybe there is an off-by-one error in the program which updates MEI to the next version, and the updating occurred twice...  Typically the error occurs after the first or first few floating elements in the measure, or perhaps the problem is only with staff 2 floating elements.

See also the fermata in measure 4 with `@startid="#d1e1480"` which points to a note in measure 2.

Also the slur in measure 6 with `@startid="#d1e1980` and `@endid="d1e2014"` which both point to notes in measure 4.

**Comment by pe-ro** [comment]
There's no requirement that so-called "floating elements" be placed in the same measure as the things they reference.  One could, for instance, place all the fermatas, slurs, etc. in the first or the final measure, or perhaps not in any measure at all, but in an appendix within the `<back>` element.  This is why it's called "stand off" markup.

On a purely practical level, in which measure should a `<slur>` element be placed when the slur involves more than one measure, the first, the last, somewhere in the middle?  No matter which one is picked, it will be "incorrect" on some level.

**Comment by craigsapp** [comment]
> There's no requirement that so-called "floating elements" be placed in the same measure as the things they reference. 

Unless they are attached via `tstamp` and not ids (without cheating and using a measure offset for the `tstamp`).

That is why I phrased the issue as " at least reasonable location."  :-)

> On a purely practical level, in which measure should a <slur> element be placed when the slur involves more than one measure, the first, the last, somewhere in the middle? No matter which one is picked, it will be "incorrect" on some level.

But regardless of slurs, fermatas from one measure have no business migrating to another measure, especially in a best-practices set of sample encodings...

For best-practice, the slur should always be stored in the measure of the start of the slur unless there is a clear need to do something non-standard.   If someone needs to know all of the slurs starting/ending/crossing for each measure, there can be an analysis step which adds additional `slur@sameas` content to every measure that a slur exists in.

**Comment by pe-ro** [comment]
> Unless they are attached via tstamp and not ids

True.

> fermatas from one measure have no business migrating to another measure

Also true, and someone should fix them at some point.  I'm not sure that someone has to necessarily be me.

> the slur should always be stored in the measure of the start of the slur

An argument could be made that the slur should be store in the measure in which the slur ends.  That way, finding the start point of the slur is a look back rather a look ahead.  This could be useful to someone attempting to write a one-pass parser.

**Comment by craigsapp** [comment]
> An argument could be made that the slur should be store in the measure in which the slur ends. That way, finding the start point of the slur is a look back rather a look ahead. This could be useful to someone attempting to write a one-pass parser.

How with the one-passness be affected by the location of the slur?  If they are consistently placed at the start or end, then one-pass parsing is possible (regardless of if it is at the start/end).
