### ISSUE TITLE
Mixture of @syl and <syl> in Bach_Ein_festeBurg.mei

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/sample-encodings#26]
Technically not a problem so nothing has to be done about this issue, but the encoding method for lyric syllables within a single file should probably be consistent as a style issue.  In Bach_Ein_festeBurg.mei, there are three cases where `note@syl` is used to encode the lyrics, while the rest of the lyrics are encoded with `note/verse/syl`.

Here is an example:

https://github.com/music-encoding/sample-encodings/blob/935382d656b0d79e5b6166663f650dfcb1787394/MEI%203.0/Music/Complete%20examples/Bach_Ein_festeBurg.mei#L649-L666

```xml
      <note xml:id="d1e1158" pname="g" oct="4" dur="8" stem.dir="up">
         <verse n="1">
            <syl>Waf</syl>
         </verse>
         <verse n="2">
            <syl>trof</syl>
         </verse>
      </note>
      <note xml:id="d1e1186" pname="f" oct="4" dur="8" stem.dir="up"/>
   </beam>
   <note xml:id="d1e1215" pname="e" oct="4" dur="4" stem.dir="up"/>
   <note xml:id="d1e1237"
         pname="d"
         oct="4"
         dur="4"
         fermata="above"
         stem.dir="up"
         syl="fen.//fen."/>
```

(also a similar case in measures 8 and 11)

The first note in the example is using elements, while the last one is using attributes.

I am presuming it should be `syl="-fen.//-fen."` for the attribute, since the syllables are at the ends of multi-syllablic words.

A problem does occur indirectly, since verovio does not (yet?) support the attribute method.  Here is what measure 4 looks like in verovio with the `fen//fen` text missing:

<img width="208" alt="screen shot 2017-10-01 at 2 10 32 pm" src="https://user-images.githubusercontent.com/3487289/31059008-5fbc970a-a6b2-11e7-9204-2461b5ca9a9d.png">

-----------

A related but more serious problem occurs in another sample work:

https://github.com/music-encoding/sample-encodings/blob/935382d656b0d79e5b6166663f650dfcb1787394/MEI%203.0/Music/Complete%20examples/Schubert_Lindenbaum.mei#L273-L290

In this work, the same lyric text is duplicated in both `note@syl` and `note/verse/syl`:

```xml
                           <note xml:id="d1e255"
                                 tstamp.ges="48p"
                                 pname="a"
                                 oct="4"
                                 dur="8"
                                 dur.ges="12p"
                                 stem.dir="up"
                                 syl="vor//heu-//Win-">
                              <verse n="1">
                                 <syl>vor</syl>
                              </verse>
                              <verse n="2">
                                 <syl wordpos="i" con="d">heu</syl>
                              </verse>
                              <verse n="3">
                                 <syl wordpos="i" con="d">Win</syl>
                              </verse>
                           </note>
```

This should be very frowned upon except for use in didactic examples to show equivalences (only short examples, and not in complete work samples, such as this :-).

I would expect processing software to automatically ignore `note@syl` in this case and use the more verbose method of `note/verse/syl`, similar to how veorvio handles things like `note@accid` and `note/accid`.

**Comment by pe-ro** [comment]
I fixed this in _Ein Feste Burg_.  I'm also expecting Verovio to make a decision about which method it will use for lyrics, so I'm leaving the other files alone for now.

**Comment by craigsapp** [comment]
Verovio should allow both methods of lyrics encoding, similar to accidental encoding.

I just added `note@syl` parsing to my mei2hum converter: https://github.com/craigsapp/humlib/commit/45c3d4977ac9f807aa1b2acb235fb13a62aaa5f8

One problem is that the `syl@wordpos` information cannot be easily extracted from `note@syl`.  For example the word `Wafen` would ideally be encoded in `note@syl` as `Wa-` and `-fen`.  This would allow for identification of the word positions as initial and terminal in this case.  Encoding as `Wa-` and `fen` does not allow that.  In other words, `Wa-` and `fen` are encoding `syl@con`,  but not `syl@wordpos`.


Verovio seems to require both `syl@con="d"` and `syl@wordpos="i|m"` in order to add a hyphen to the lyrics, so the `@wordpos` information has to be determined correctly when converting from `note@syl` data into `note/verse/syl` for printing with verovio.

Examples:

```xml
  <syl con="d" wordpos="i">un</syl>
```
verovio renders as `un-`

```xml
  <syl wordpos="i">un</syl>
```

verovio renders as `un`


```xml
  <syl con="d">un</syl>
```

verovio renders as `un`

```xml
  <syl con="d" wordpos="t">un</syl>
```

verovio renders as `un`

**Comment by pe-ro** [comment]
If the position of the syllable in the word is known, then it shouldn't be difficult to include dashes as necessary during conversion to MEI.  I may be able to write some XSLT for creating `@syl` data from `<syl>` elements, but not this week.  :smile:

**Comment by craigsapp** [comment]
> If the position of the syllable in the word is known, then it shouldn't be difficult to include dashes as necessary during conversion to MEI. 

The problem is the other way around :-).  Going from `syl@wordpos` to `syl@con` is easy, while the other direction is not.  The other direction requires ordering all syllables for the text, and then looking at adjacent syllables to infer the `@wordpos` information.

You are encoding `@syl` with implied `syl@con` by adding a dash after each syllable.  But since you do not add a prefix dash on the following syllable, the information being encoded is `syl@con` and not `syl@wordpos`.   Humdrum encodes `syl@wordpos` and I need the `@wordpos` information to display properly in verovio,  so I will eventually have to add a parser to convert from `@con` data to `@wordpos` in the mei2hum converter for `note@syl`...

**Comment by pe-ro** [comment]
The file was fixed and Verovio developments have likely made the discussion moot.  Closing for now, but always "re-openable".
