### ISSUE TITLE
Dynamic wrapped in rend

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/sample-encodings#35]
Why is this dynamic from measure 1 in the file:

https://github.com/music-encoding/sample-encodings/blob/master/MEI_3.0/Music/Complete_examples/Saint-Saens_LeCarnevalDesAnimmaux.mei

wrapped in a `<rend>` element?:

```
                     <dynam tstamp="1" place="below" staff="1">
                        <rend>pp</rend>
                     </dynam>
```

**Comment by pe-ro** [comment]
>Why is this dynamic from measure 1 in the file:
>
>https://github.com/music-encoding/sample-encodings/blob/master/MEI_3.0/Music/Complete_examples/Saint-Saens_LeCarnevalDesAnimmaux.mei wrapped in a <rend> element?

Most likely, this is an artifact of the conversion from MusicXML.

Technically, it's not an error, so my inclination is to leave it.
