### ISSUE TITLE
Missing chord durations

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/sample-encodings#37]
In the file:

https://github.com/music-encoding/sample-encodings/blob/master/MEI_3.0/Music/Complete_examples/Ives_TheCage.mei

The chords do not posses durations, such as:

```xml
                           <chord>
                              <note pname="a" oct="4" dur="4" stem.dir="up"/>
                              <note pname="d" oct="5" dur="4" stem.dir="up"/>
                           </chord>
```

Is this legal MEI 3.0 behavior?  Verovio ignores `chord/note@dur` -- perhaps it is a MEI 4.0 feature?

In the current development version of verovio (using MEI 4.0 pre-release), this is how it needs to be encoded:

```xml
                           <chord dur="4" stem.dir="up">
                              <note pname="a" oct="4" accid.ges="n" />
                              <note pname="d" oct="5" accid.ges="n" />
                           </chord>
```

**Comment by pe-ro** [comment]
@craigsapp, This is legal MEI behavior -- the duration can be given on the chord or on the individual notes.

Is this still a problem in Verovio?

**Comment by lpugin** [comment]
Verovio does not ignore `chord/note@dur`. It takes it into account for chords with multiple note durations. However, it does expect the longest duration to be given in `chord@dur`. So 
```xml
<chord dur="2">
    <note pname="a" oct="4">
    <note pname="d" oct="5" dur="4"/>
</chord>
```
works, but not chords with no `@dur` at all.

**Comment by bwbohl** [comment]
Am I right to assume this issue can be considered "solved"?

**Comment by rettinghaus** [comment]
@bwbohl I feel bold today and will do so.
