### ISSUE TITLE
Unmatched PDF in Complete_examples

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/sample-encodings#40]
The file:

https://github.com/music-encoding/sample-encodings/blob/master/MEI_3.0/Music/Complete_examples/Debussy_Children'sCorner.pdf

Does not have a matching MEI file.

-------------

Also the file `McFerrin_Don't_ worry.pdf` has a spurious space in the filename (The matching MEI file does not have this space).

**Comment by bwbohl** [comment]
I think we should delete the Children's Corner PDF from the sample files and also delete the whitespace from the McFerring PDF file name
