### ISSUE TITLE
staff without @n in Telemann concerto example

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/sample-encodings#41]
In this file:

https://github.com/music-encoding/sample-encodings/blob/master/MEI_3.0/Music/Complete_examples/Telemann_Concert.mei#L5919

Line 5919, there is a staff without `@n` in measure 21.  The other staves in the file have `@n`:

```xml
   <staff n="1"/>
   <staff n="2"/> 
   <staff n="3"/>
   <staff n="4"/>
   <staff n="5"/>
   <staff/>
```

This also occurs in measure 33, 48, and 55.

Is that allowed?  And if not, have these files been validated?  

If staves are allowed to not have `@n`, then presumably the sequence of the `<staff>` in the measure indicates which staff it is?  In this case the `<staff>` would be assigned to staff 6, which is correct.  What should happen if there are only 5 staves in the `<scoreDef>` and such a `<staff>` is encountered?

---

Somewhat more problematic, there are a couple of  `<dir>` without `@n` in measure 103 and 138.  These are for the movement designation markers (which are related to the `staff="all"` situation).  In measure 103 the text is "3 - Largo (Organ solo)" and in m 138 the text is "(4 - Vivace).

Or somehow the text was accidentally repeated, since they are placed on staff 1, then given again staffless:

```xml
                     <dir tstamp="4" place="above" staff="1">
                        <rend fontsize="8.6" fontweight="bold">3 - Largo (Organ solo)</rend>
                     </dir>
                     <dir tstamp="3" place="above">
                        <rend fontsize="8.6" fontweight="bold">3 - Largo (Organ solo)</rend>
                     </dir>
```

```xml
                     <dir tstamp="1" place="above" staff="1">
                        <rend fontsize="8.6" fontweight="bold">4 - Vivace</rend>
                     </dir>
                     <dir tstamp="1" place="above">
                        <rend fontsize="8.6" fontweight="bold">4 - Vivace</rend>
                     </dir>
```

**Comment by pe-ro** [comment]
re: `<staff>` without `@n`, yes, this is allowed.  But, we can require `staff/@n` if you think it's a huge problem.  It's not required now in order to facilitate hand-encoding, but clearly that's an issue.  😀 

The same goes for `dir/@staff`.

We can put the requirements in the schema or in Schematron rules.  I'm open to suggestions regarding which way to go.

**Comment by craigsapp** [comment]
For staves without `@n`, I do not have a problem.  But somewhere, particularly in guidelines for people implementing MEI parsers, how to handle such situations should be defined.  In this sort of case, there would be an implicit `@n` added which increments the staff number by one from the previous staff in the measure list.

However, mixing staves with and without `@n` in the same measure or file is not so great:

```
   <staff n="1"/>
   <staff n="2"/> 
   <staff n="3"/>
   <staff n="4"/>
   <staff n="5"/>
   <staff/>
```

Preferably all staves would include `@n` in a file, or none of them would.

Of course for tighter control of the data (automatic error checking), it would be better if `@n` is required.  Also requiring it would cause fewer headaches when manipulating the contents of an MEI file, such as when extracting parts, or assigning floating elements to staves with implicit staff numbers.

If staff numbers are allowed to be implicit, then floating elements inside of `<staff>` should be allowed (which they currently are not).  Otherwise, a floating element with an explicit staff number would have to be linked to a staff with an implicit staff number.


This encoding:

```xml
<measure>
   <staff/>
   <staff/>
   <staff/>
</measure>
```

would be inferred to be:

```xml
<measure>
   <staff n="1"/>
   <staff n="2"/>
   <staff n="3"/>
</measure>
```

And this:

```xml
<measure>
   <staff n="1"/>
   <staff/>
   <staff n="3"/>
</measure>
```

 would be inferred to be:

```xml
<measure>
   <staff n="1"/>
   <staff n="2"/>
   <staff n="3"/>
</measure>
```

Are staves allowed to be placed into the measure in any order?  If so, then this encoding would cause a problem:

```xml
<measure>
   <staff n="1"/>
   <staff/>
   <staff n="2"/>
</measure>
```

What is the staff assignment of the `<staff/>`?  If it is "2", then there is a problem since there is already a staff 2 entry.  If there are three staves in the system, it could be inferred to be staff 3, but this sort of situation should be disallowed.

or another variation:


```xml
<measure>
   <staff/>
   <staff n="2"/>
   <staff n="1"/>
</measure>
```

The Schematron rules should be able to assign implicit staff numbers to such staff elements, and should double check the scoreDef to ensure that the implicit staff number is in the range of stave numbers being encoded.

-----------

For `<dir>` without `@staff` (or `@startid`/`@plist`), that is more problematic.  Either the dir should be marked as invalid because it is not attached to a staff, or it should be applied to all staves. Floating elements are not grouped or ordered by staff, so the staff assignment cannot be inferred by the previous floating element in the `<measure>`.  It is probably best to require `@staff` for dirs.

**Comment by pe-ro** [comment]
Reopening this to make sure it gets addressed.

**Comment by pe-ro** [comment]
Closing here, taking the discussion to the music-encoding repo.
