### ISSUE TITLE
schematron warnings

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/sample-encodings#52]
At the current state the sample encodings for MEI v4.0.0 throw 266 schematron warning on validation theses are:
- mainly: It is recommended that the agent responsible for the change be recorded in a resp attribute or in a name, corpName, or persName element in the respStmt element.
- some: The value in @resp should correspond to the @xml:id attribute of an element within the metadata header.
- some: At least one element pair (a resp element and a name-like element) is recommended. Alternatively, each name-like element may have a @role attribute.

Should we try fix those or ignore them, as they are merely warnings?

**Comment by rettinghaus** [comment]
Fixing those would be nice.
