### ISSUE TITLE
<tempo> vs. <dir>

### ISSUE THREAD

**Issue by th-we** [music-encoding/sample-encodings#53]
The specs for `<tempo>` say:

> Text and symbols descriptive of tempo, mood, or style, e.g., "allarg.", "a tempo", "cantabile", "Moderato", "♩=60", "Moderato ♩ =60").

There are a number of "a tempo"s in the samples, however all of them are in `<dir>`, not `<tempo>`.  From the 4.0 samples:

    MEI_4.0/Music/Complete_examples/Saint-Saens_LeCarnevalDesAnimaux.mei
    MEI_4.0/Music/Complete_examples/Rimsky-Korsakov_StringQuartet_B.mei
    MEI_4.0/Music/Complete_examples/Hummel_Concerto_for_trumpet.mei
    MEI_4.0/Music/Complete_examples/Schumann_Op.41.mei
    MEI_4.0/Music/Complete_examples/Borodin_StringTrio_g.mei
    MEI_4.0/Music/Complete_examples/Chopin_Etude_op.10_no.9.mei
    MEI_4.0/Musical-features/snippets/slur_element.mei

There are other examples as well (like "rit." etc.). `<tempo>` was only used for absolute tempos (with the exception of "Un peu moins vite" in Golliwog's Cakewalk, though in the same file, "cédez" and "a tempo" are in `<dir>`).

I thinks all the relative tempo markings should be in `<tempo>` as well – or should we make the de-facto standard the official standard and change the specs?

**Comment by rettinghaus** [comment]
Yes, the 'relative' tempos should be encoded as `<tempo>`, too. The mediocre encoding could probably be traced back to the original MusicXML files. 

I changed that already in *my* Cakewalk:
https://github.com/rettinghaus/MEILER/blob/master/examples/Debussy_Golliwogg'sCakewalk.mei

**Comment by th-we** [comment]
So, here is a list of all values of `<dir>` elements:

[dir-values.txt](https://github.com/music-encoding/sample-encodings/files/3546597/dir-values.txt)

There are a total of 6014 `<dir>` elements in the repo, but only 291 different values. The latter is a reasonable number to go through and determine out if something is actually `<tempo>` or `<dynam>`. We could then try to automate replacing the tag name.  Some are inside `<section>` or `<ending>` which is not allowed for `<dynam>` or `<tempo>`, those would have to be "transplanted". Maybe we could validate everything and fix all remaining errors manually?

**Comment by th-we** [comment]
So, here is a list of all values of `<dir>` elements (in the 4.0 samples):

[dir-values.txt](https://github.com/music-encoding/sample-encodings/files/3547098/dir-values.txt)

There are a total of 1534 `<dir>` elements in the repo, but only 272 different values. I created pull requests #54 and #55 to fix two of the problems in that list, but that's too tedious. I'd suggest going through the list of values, determine what should actually be `<tempo>` or `<dynam>`, and then try to automate replacement of tag names.

XSLT is not such a good option for this because we risk a lot of reformatting and very non-transparent commits.  So I guess a little script would be the best option.

Some `<dir>`s are inside `<section>` or `<ending>` which is not allowed for `<dynam>` or `<tempo>`. But we'd find those places by validating everything (also to find incompatible attributes).

Anyone volunteering to sort out the list?

**Comment by rettinghaus** [comment]
Those files should be ok, so closing this for now. We can reopen this, if there are more complaints.
