### ISSUE TITLE
Broken grand staff in Telemann Concert

### ISSUE THREAD

**Issue by th-we** [music-encoding/sample-encodings#59]
Starting from m. 59, I suppose there was some broken conversion from MusicXML. [All the organ part is written on a single staff](https://github.com/music-encoding/sample-encodings/blob/9ebd87b354e992eb6c061eded1c989640b889b05/MEI_4.0/Music/Complete_examples/Telemann_Concert.mei#L6290) there.

**Comment by bwbohl** [comment]
thanks for spotting!
Want to provide a fix? ;-)
