### ISSUE TITLE
Errors in Scott Joplin Maple Leaf Rag

### ISSUE THREAD

**Issue by heinzr** [music-encoding/sample-encodings#61]
I found the following errors in the MEI sample encoding of Scott Joplin's Maple Leaf Rag:
 - measure 8 and 42: missing rest in staff 2/layer 2
 - measure 14, 44, 48: the clef change is not handled correctly.

I have put the corrections into the attached files. 

My confidence in these corrections is limited due to my lack of experience with MEI. They seem to render correctly, though.

[Joplin_Maple_leaf_Rag_corrected.zip](https://github.com/music-encoding/sample-encodings/files/5618254/Joplin_Maple_leaf_Rag_corrected.zip)

**Comment by rettinghaus** [comment]
Thanks for reporting this. I created a correpsonding pull request in #62.
