### ISSUE TITLE
Update tag and README to latest release

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/sample-encodings#63]
The README is still talking about MEI 3 as the latest release. That could be confusing ;)

EDIT: Also the one and only release tag is 3.0.0

**Comment by bwbohl** [comment]
nice catch :-/

**Comment by bwbohl** [comment]
I'm starting to wonder wether we should also reintegrate the sample-encodings into the music-encoding repo… @music-encoding/core-contributors any thoughts?
