### ISSUE TITLE
Incorrect accidental in Joplins Maple Leave Rag

### ISSUE THREAD

**Issue by apacha** [music-encoding/sample-encodings#65]
I've spotted a tiny error in https://github.com/music-encoding/sample-encodings/blob/master/MEI_4.0/Music/Complete_examples/Joplin_Maple_leaf_Rag.mei - Measure 9 and similar measures have a wrong natural sign on the A instead of on the B.

**Comment by rettinghaus** [comment]
@apacha Thanks for the hint!
