### ISSUE TITLE
Create v5.0 sample-encodings

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/sample-encodings#76]
- [x] updated sample-encodings to v5 using the mei40to50.xsl
- [x] validate with generated schema
- [x] publish

**Comment by bwbohl** [comment]
use https://github.com/music-encoding/encoding-tools/pull/30

**Comment by bwbohl** [comment]
fix customization-specific version-numbers compare [#1319](https://github.com/music-encoding/music-encoding/pull/1319)

**Comment by rettinghaus** [comment]
@bwbohl there are now some duplicated IDs in several files on the `release/v5.0` branch, especially `Doc_starts_with_meiCorpus.mei`

**Comment by bwbohl** [comment]
> @bwbohl there are now some duplicated IDs in several files on the `release/v5.0` branch, especially `Doc_starts_with_meiCorpus.mei`

Thanks for checking. Unfortunately, some new settings in my oXygen XML prevented proper validation of the IDs… and unfortunately the MEI 4 -> 5 XSLT created the application entry in every `encodingDesc` which is especially a problem with `meiCorpus` now I see why the generated IDs were random IDs before…

**Comment by bwbohl** [comment]
closed with 5c07e5f3bdcaeca4dbabcd738f0b069a3c50929f
